TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 0.25
  acc_lim_x: 2.5
  acc_lim_Y: 2.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.8
  yaw_goal_tolerance: 0.25